version: "3.9"
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
services:
  db:
    container_name: playlist-db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playlist
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d playlist -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

  playlist-service:
    build: .
    container_name: playlist-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  migrator:
    image: golang:1.23.4
    container_name: playlist-migrator
    working_dir: /app
    volumes:
      - ./migrations:/app/migrations
    entrypoint:
      - /bin/sh
      - -c
      - >
        go install github.com/pressly/goose/v3/cmd/goose@latest &&
        goose -dir /app/migrations postgres "postgres://user:password@db:5432/playlist?sslmode=disable" up
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network